function [tAccel, accel, tForce, force] = ImportCSV(filename, dataLines)
%IMPORTFILE Import data from a text file
%  UNTITLED = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the numeric data.
%
%  UNTITLED = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  Untitled = importfile("C:\Users\kaebi\OneDrive - mci4me.at\03_MCI Master\3.Semester_WS2021\Project 2\SoftwareRepository\Raspberry\Data\2021-12-22_TestData\Test_1\2021-12-22_08-59-11.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 26-Dec-2021 10:59:23

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 4);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Times", "Accelerationmg", "Times_1", "ForceN"];
opts.VariableTypes = ["double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
rawData = readtable(filename, opts);

%% Convert to output type
rawData = table2array(rawData);
tAccel = rawData(:,1);
accel = rawData(:,2);
tForce  = rawData(:,3);
force = rawData(:,4);

end