function [Times, Accelerationmg, ForceN] = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  [TIMES, ACCELERATIONMG, FORCEN] = IMPORTFILE(FILENAME) reads data
%  from text file FILENAME for the default selection.  Returns the data
%  as column vectors.
%
%  [TIMES, ACCELERATIONMG, FORCEN] = IMPORTFILE(FILE, DATALINES) reads
%  data for the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  [Times, Accelerationmg, ForceN] = importfile("C:\Users\Felbermayr Simon\OneDrive - mci4me.at\01_Master\3.Semester\Project_2\Data\2021-12-15_11-00-51.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 15-Dec-2021 12:03:34

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Times", "Accelerationmg", "ForceN"];
opts.VariableTypes = ["double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
tbl = readtable(filename, opts);

%% Convert to output type
Times = tbl.Times;
Accelerationmg = tbl.Accelerationmg;
ForceN = tbl.ForceN;
end